name: Build and Publish Wheel Package

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонируем репозиторий
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Укажите вашу версию Python

    # Шаг 3: Устанавливаем зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    # Шаг 4: Собираем пакет
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    # Шаг 5: Создаем новый тег на основе хеша коммита
    - name: Create a tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA:0:7}"  # Формат: vYYYYMMDDHHMMSS-HASH
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}

    # Шаг 6: Создаем релиз на GitHub
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag_name }}  # Используем динамически созданный тег
        files: dist/*.whl  # Загружаем только .whl файлы из dist/